spring.application.name=demoTcc
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://143.106.241.4:3306/cl204093
spring.datasource.username=cl204093
spring.datasource.password=cl*05022008
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=samufilho1@gmail.com
spring.mail.password=ybya axoq jvjs ikcw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

monitoria.api.base-url=http://localhost:8080/apiMonitoria
server.port=8080
